name: .NET MAUI CI/CD

on:
  push:
    branches:
      - develop-cicd
  pull_request:
    branches:
      - develop-cicd

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Install Workloads
        run: dotnet workload install maui android
        
      - name: Restore Dependecies
        run: dotnet restore
        
      - name: Build Project
        run: dotnet build --no-restore
            
      - name: Publish Project
        run: dotnet publish -c:Release -f:net7.0-android --output /p:AndroidPackageFormat=apk /p:EnableLLVM=false /p:RunAOTCompilation=true /p:AndroidEnableProfiledAot=false
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apkBuild
          path: 
            ./**/*.aab
            ./**/*.apk
